apps/automation/urls.py
# https://www.javatpoint.com/django-crud-example

from django.urls import path
from . import views

app_name = 'automation_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:automation_id>/', views.edit, name='edit'),
    path('delete/<int:automation_id>/', views.delete, name='delete'),
]

crudexample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.automation.urls')),
]

apps/automation/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Automation(models.Model):
    gitrepo = models.CharField(max_length=100)
    gitbranch = models.CharField(max_length=100)
    env = models.CharField(max_length=100)
    tags = models.CharField(max_length=100)
    processes = models.CharField(max_length=100)
    googlechaturl = models.CharField(max_length=100)
    reportpath = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = ("Automation")
        verbose_name_plural = ("Automations")
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

    # This method name: 'get_absolute_url()' is reserved in django
    # def get_absolute_url(self):
    #     return reverse("automation_app:edit", kwargs={"automation_id": self.pk})

    def get_absolute_url_edit(self):
        return reverse("automation_app:edit", kwargs={"automation_id": self.pk})

    def get_absolute_url_delete(self):
        return reverse("automation_app:delete", kwargs={"automation_id": self.pk})

apps/automation/forms.py
from django import forms
from .models import Automation


class AutomationForm(forms.ModelForm):
    class Meta:
        model = Automation
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(AutomationForm, self).__init__(*args, **kwargs)
        self.fields['gitrepo'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Repo...'})
        self.fields['gitbranch'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Branch...'})
        self.fields['env'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Env...'})
        self.fields['tags'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Tags...'})
        self.fields['processes'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Processes...'})
        self.fields['googlechaturl'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'GoogleChatUrl...'})
        self.fields['reportpath'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Report...'})

apps/automation/views.py
from django.shortcuts import render
from .forms import AutomationForm
from .models import Automation
from django.shortcuts import redirect, get_object_or_404
import xml.etree.ElementTree as ET
import os


# Create your views here.
def index(request):
    automations = Automation.objects.all()
    return render(request, 'automation/index.html', {'automation1': automations})


def add(request):
    if request.method == "POST":
        form = AutomationForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                displaytrans(request)
                external1(request)
                return redirect('automation_app:index')
            except:
                pass
    else:
        form = AutomationForm()
    return render(request, 'automation/add.html', {'form': form})


def edit(request, automation_id):
    automation = get_object_or_404(Automation, id=automation_id)
    form = AutomationForm(request.POST, instance=automation)
    if form.is_valid():
        try:
            form.save()
            displaytrans(request)
            external1(request)
            return redirect('automation_app:index')
        except:
            pass
    return render(request, 'automation/edit.html', {'automation1': automation})


def delete(request, automation_id):
    automation = Automation.objects.get(id=automation_id)
    try:
        automation.delete()
    except:
        pass
    return redirect('automation_app:index')


def external1(request):
    os.system('crudexample.sh')


def displaytrans(request):
    info = Automation.objects.all().first()
    print(info.gitrepo)
    print(info.gitbranch)
    print(info.env)
    print(info.tags)
    print(info.processes)
    print(info.googlechaturl)
    tree = ET.parse('mylocalconfig.xml')
    root = tree.getroot()
    for node in root.findall('.//hudson.plugins.git.UserRemoteConfig/url'):
        node.text = info.gitrepo
        print(node.text)
    for node1 in root.findall('.//hudson.plugins.git.BranchSpec/name'):
        node1.text = info.gitbranch
        print(node1.text)
    for node1 in root.findall('.//hudson.model.StringParameterDefinition/defaultValue'):
        node1.text = info.env
        print(node1.text)
    for node1 in root.findall('.//hudson.model.StringParameterDefinition/defaultValue'):
        node1.text = info.tags
        print(node1.text)
    for node1 in root.findall('.//hudson.model.StringParameterDefinition/defaultValue'):
        node1.text = info.processes
        print(node1.text)
    for node1 in root.findall('.//hudson.model.StringParameterDefinition/defaultValue'):
        node1.text = info.googlechaturl
        print(node1.text)
    tree.write('mylocalconfig.xml')

apps/automation/templates/automation/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="description" content="Application by Ragu Sekaran">
	<meta name="author" content="Ragu Sekaran">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<title>{% block title %}{% endblock %}</title>
	<link rel="apple-touch-icon" href=""> {% load static %}

	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
	 crossorigin="anonymous">

	<!-- Link to Bootstrap CSS file -->
	<link rel="stylesheet" href="{% static 'automation/css/vendor/bootstrap/bootstrap.min.css' %}" type="text/css">

	<!-- Link to Materialize CSS file -->
	<!-- <link rel="stylesheet" href="{% static 'automation/css/vendor/materialize/materialize.min.css' %}" type="text/css"> -->

	<!-- Link to your favicon.ico file -->
	<link rel="shortcut icon" href="{% static 'automation/img/favicon.ico' %}" type="image/x-icon">

	<!-- Link to your css file -->
	<link rel="stylesheet" href="{% static 'automation/css/main.css' %}" type="text/css">

</head>

<body>
	{% block content %}{% endblock %}


	<!-- Link to Materialize JS file -->
	<!-- <script src="{% static 'automation/js/vendor/materialize/materialize.min.js' %}"></script> -->

	<!-- JQuery comes first in the list -->
	<script src="{% static 'automation/js/vendor/bootstrap/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'automation/js/vendor/bootstrap/popper.min.js' %}"></script>
	<script src="{% static 'automation/js/vendor/bootstrap/bootstrap.min.js' %}"></script>

	<!-- Link to your js file -->
	<script src="{% static 'automation/js/main.js' %}"></script>
</body>

</html>

apps/automation/templates/automation/_base_add_edit.html
{% extends 'automation/_base.html' %}
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<form method="POST" class="post-form" {% block action %} {% endblock %}>
	{% csrf_token %}
	<div class="container">
		<br>
		<div class="form-group row">
			<label class="col-form-label"></label>
			<div class="col-sm-4">
				{% block heading %}
				{% endblock %}
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">GIT Repo:</label>
			<div class="col-sm-4">
				{% block gitrepoblock %}
				{% endblock %}
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Git Branch:</label>
			<div class="col-sm-4">
				{% block gitbranchblock %}
				{% endblock %}
			</div>
		</div>
        <div class="form-group row">
			<label class="col-sm-2 col-form-label">Env:</label>
			<div class="col-sm-4">
				{% block envblock %}
				{% endblock %}
			</div>
		</div>
        <div class="form-group row">
			<label class="col-sm-2 col-form-label">Tags:</label>
			<div class="col-sm-4">
				{% block tagsblock %}
				{% endblock %}
			</div>
		</div>
        <div class="form-group row">
			<label class="col-sm-2 col-form-label">Processes:</label>
			<div class="col-sm-4">
				{% block processesblock %}
				{% endblock %}
			</div>
		</div>
        <div class="form-group row">
			<label class="col-sm-2 col-form-label">Google Chat URL:</label>
			<div class="col-sm-4">
				{% block googlechaturlblock %}
				{% endblock %}
			</div>
		</div>
		<div class="form-group row">
			<label class="col-sm-2 col-form-label">Report Path:</label>
			<div class="col-sm-4">
				{% block reportpathblock %}
				{% endblock %}
			</div>
		</div>
		<div class="form-group row">
			<label class="col-form-label"></label>
			<div class="m-3">
				{% block record %}
				{% endblock %}
			</div>
		</div>
	</div>
</form>
{% endblock %}

apps/automation/templates/automation/add.html
{% extends 'automation/_base_add_edit.html' %}

{% block title %}
Add Jenkins Job details...
{% endblock %}

{% block action %}
action="{% url 'automation_app:add' %}"
{% endblock %}

{% block heading %}
<h3>Enter Jenkins Job details...</h3>
{% endblock %}

{% block gitrepoblock %}
{{ form.gitrepo }}
{% endblock %}

{% block gitbranchblock %}
{{ form.gitbranch }}
{% endblock %}

{% block envblock %}
{{ form.env }}
{% endblock %}

{% block tagsblock %}
{{ form.tags }}
{% endblock %}

{% block processesblock %}
{{ form.processes }}
{% endblock %}

{% block googlechaturlblock %}
{{ form.googlechaturl }}
{% endblock %}

{% block reportpathblock %}
{{ form.reportpath }}
{% endblock %}

{% block record %}
<button type="submit" class="btn btn-primary">Create Job</button>
{% endblock %}

apps/automation/templates/automation/delete.html
{% extends 'automation/_base.html' %}
{% load static %}

{% block title %}
Delete jenkins job details...
{% endblock %}

{% block content %}
{% endblock %}

apps/automation/templates/automation/edit.html
{% extends 'automation/_base_add_edit.html' %}

{% block title %}
Edit Jenkins Job Details...
{% endblock %}

{% block action %}
action="{% url 'automation_app:edit' employee.id %}"
{% endblock %}

{% block heading %}
<h3>Update Jenkins Job Details...</h3>
{% endblock %}

{% block gitrepoblock %}
<input type="text" name="gitrepo" id="id_gitrepo" class="form-control" required maxlength="100" value="{{ employee.gitrepo }}" />
{% endblock %}

{% block gitbranchblock %}
<input type="text" name="gitbranch" id="id_gitbranch" class="form-control" required maxlength="100" value="{{ employee.gitbranch }}" />
{% endblock %}

{% block envblock %}
<input type="text" name="env" id="id_env" class="form-control" required maxlength="100" value="{{ employee.env }}" />
{% endblock %}

{% block tagsblock %}
<input type="text" name="tags" id="id_tags" class="form-control" required maxlength="100" value="{{ employee.tags }}" />
{% endblock %}

{% block processesblock %}
<input type="text" name="processes" id="id_processes" class="form-control" required maxlength="100" value="{{ employee.processes }}" />
{% endblock %}

{% block googlechaturlblock %}
<input type="text" name="googlechaturl" id="id_googlechaturl" class="form-control" required maxlength="100" value="{{ employee.googlechaturl }}" />
{% endblock %}

{% block reportpathblock %}
<input type="text" name="reportpath" id="id_reportpath" class="form-control" required maxlength="100" value="{{ employee.reportpath }}" />
{% endblock %}

{% block record %}
<button type="submit" class="btn btn-primary">Update Job</button>
{% endblock %}

apps/automation/templates/automation/index.html
{% extends 'automation/_base.html' %}
{% load static %}

{% block title %}
Jenkins Job List...
{% endblock %}

{% block heading %}
<h3>IHerb Automation Dashboard</h3>
{% endblock %}

{% block content %}
    <center><h3>IHerb Automation Dashboard</h3></center>
<table class="table table-striped table-bordered table-sm">
	<thead class="thead-dark">
		<tr>
			<th>TestCase ID</th>
			<th>GIT Repo</th>
			<th>GIT Branch</th>
            <th>Env</th>
            <th>Tags</th>
            <th>Processes</th>
            <th>GoogleChatUrl</th>
			<th>Report Path</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for automation in automations %}
		<tr>
            <td>{{ automation.id }}</td>
			<td>{{ automation.gitrepo }}</td>
			<td>{{ automation.gitbranch }}</td>
			<td>{{ automation.env }}</td>
            <td>{{ automation.tags }}</td>
            <td>{{ automation.processes }}</td>
            <td>{{ automation.googlechaturl }}</td>
			<td><a href=" {{ automation.reportpath }}" target="_blank">Click Me To See The Allure Report</a></td>
			<td>
				<center>
					<a href="{{ automation.get_absolute_url_edit }}"><i class="fas fa-pencil-alt mr-3"></i></a>
					<a href="{{ automation.get_absolute_url_delete }}"><i class="fas fa-trash-alt"></i></a>
				</center>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<br>
<br>
<center><a href="{% url 'automation_app:add' %}" class="btn btn-primary">Add New Job</a></center>
{% endblock %}